"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { getSnapshot, snapshots, tradingDates } from "@/lib/real-data";
import { DailyStockAnalysis, Rating } from "@/lib/types";

const money = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value);
const shortDate = (date: string) => `${Number(date.slice(5, 7))}/${Number(date.slice(8, 10))}`;
const scoreColor = (score: number) => score >= 85 ? "var(--positive)" : score >= 75 ? "var(--accent)" : "var(--warning)";
const ratingLabel: Record<Rating,string> = { "Strong Buy":"強力買進", Buy:"買進", Watch:"觀察", Hold:"持有", Avoid:"避開" };
const industryEnglish: Record<string,string> = { "AI 伺服器":"AI Servers", "半導體":"Semiconductors", "電子零組件":"Electronic Components", "散熱":"Thermal Solutions", PCB:"PCB", "電源與能源":"Power & Energy", "記憶體":"Memory" };

function RankMove({ current, previous }: { current: number; previous: number | null }) {
  if (previous === null) return <span className="move new">新進</span>;
  const delta = previous - current;
  if (!delta) return <span className="move">—</span>;
  return <span className={`move ${delta > 0 ? "up" : "down"}`}>{delta > 0 ? "↑" : "↓"} {Math.abs(delta)}</span>;
}

function KpiCard({ label, value, delta, hint }: { label: string; value: string | number; delta: number; hint: string }) {
  return <article className="kpi" title={hint}><div><span>{label}</span><b>ⓘ</b></div><strong>{value}</strong><p className={delta >= 0 ? "positive" : "negative"}>{delta >= 0 ? "↑" : "↓"} {Math.abs(delta)}% <small>vs previous session</small></p></article>;
}

function RankingBars({ stocks, selected, onSelect }: { stocks: DailyStockAnalysis[]; selected: string; onSelect: (ticker: string) => void }) {
  return <div className="ranking-bars">{stocks.map(stock => <button key={stock.ticker} className={selected === stock.ticker ? "active" : ""} onClick={() => onSelect(stock.ticker)}><span>{stock.stockName}<small>{stock.ticker}</small></span><i><em style={{ width: `${stock.garpScore}%`, background: scoreColor(stock.garpScore) }} /></i><b>{stock.garpScore}</b></button>)}</div>;
}

function Scatter({ stocks, selected, onSelect }: { stocks: DailyStockAnalysis[]; selected: string; onSelect: (ticker: string) => void }) {
  return <div className="scatter-wrap"><div className="ideal-zone">HIGH-GROWTH FAIR-VALUE ZONE</div><svg viewBox="0 0 620 290" role="img" aria-label="PEG versus EPS growth scatter plot"><line x1="48" y1="250" x2="600" y2="250"/><line x1="48" y1="20" x2="48" y2="250"/>{stocks.map(stock => { const x = Math.max(55,Math.min(590,55 + ((stock.peg - .2) / 3) * 520)); const y = Math.max(25,Math.min(245,245 - ((stock.forecastEpsGrowth - 0) / 60) * 210)); return <g key={stock.ticker} onClick={() => onSelect(stock.ticker)} className={selected === stock.ticker ? "selected" : ""}><circle cx={x} cy={y} r="12"><title>{stock.stockName}: PEG {stock.peg}, EPS growth proxy {stock.forecastEpsGrowth}%</title></circle><text x={x} y={y - 16}>{stock.ticker}</text></g>; })}<text x="300" y="282" className="axis">PEG → lower is better</text><text x="-168" y="14" transform="rotate(-90)" className="axis">EPS growth proxy (%)</text></svg></div>;
}

function FairValueChart({ stocks }: { stocks: DailyStockAnalysis[] }) {
  const max = Math.max(...stocks.map(s => s.fairValueHigh));
  return <div className="fair-chart">{stocks.slice(0, 6).map(stock => <div key={stock.ticker}><span>{stock.ticker}</span><i><em className="range" style={{ left: `${stock.fairValueLow / max * 100}%`, width: `${(stock.fairValueHigh - stock.fairValueLow) / max * 100}%` }} /><b style={{ left: `${stock.currentPrice / max * 100}%` }} title={`Current NT$${money(stock.currentPrice)}`} /></i><small>NT${money(stock.fairValueBase)}</small></div>)}</div>;
}

function ScoreComposition({ stock }: { stock: DailyStockAnalysis }) {
  const values = [["Valuation", stock.valuationScore], ["Growth", stock.growthScore], ["Quality", stock.qualityScore], ["Cash flow", stock.cashFlowScore], ["Expectations", stock.expectationScore], ["Risk control", 100 - stock.riskScore]] as const;
  return <div className="score-list">{values.map(([label, value]) => <div key={label}><span>{label}</span><i><em style={{ width: `${value}%` }} /></i><b>{value}</b></div>)}</div>;
}

function EpsChart({ stock }: { stock: DailyStockAnalysis }) {
  const max = Math.max(...stock.epsHistory); const points = stock.epsHistory.map((v, i) => `${35 + i * 110},${210 - v / max * 170}`).join(" ");
  return <svg className="line-chart" viewBox="0 0 570 240" role="img" aria-label="Quarterly EPS trend"><line x1="30" y1="210" x2="550" y2="210"/><polyline points={points}/>{stock.epsHistory.map((v, i) => <g key={i}><circle cx={35 + i * 110} cy={210 - v / max * 170} r="4"><title>Quarterly EPS {v}</title></circle><text x={35 + i * 110} y="230">{["25Q1","25Q2","25Q3","25Q4","26Q1"][i]}</text></g>)}</svg>;
}

function SectorChart({ stocks }: { stocks: DailyStockAnalysis[] }) {
  const sectors = Object.entries(stocks.reduce<Record<string, number>>((acc, s) => ({ ...acc, [s.industry]: (acc[s.industry] ?? 0) + 1 }), {}));
  return <div className="sector-list">{sectors.map(([sector, count]) => <div key={sector}><span>{industryEnglish[sector] ?? sector}</span><i><em style={{ width: `${count / stocks.length * 100}%` }} /></i><b>{count}</b></div>)}</div>;
}

function StockTable({ stocks, onSelect }: { stocks: DailyStockAnalysis[]; onSelect: (ticker: string) => void }) {
  const [query, setQuery] = useState(""); const [industry, setIndustry] = useState("All"); const [rating, setRating] = useState("All"); const [sort, setSort] = useState<"rank" | "garpScore" | "upsidePercent">("rank");
  const industries = [...new Set(stocks.map(s => s.industry))];
  const filtered = stocks.filter(s => `${s.stockName}${s.ticker}`.toLowerCase().includes(query.toLowerCase()) && (industry === "All" || s.industry === industry) && (rating === "All" || s.rating === rating)).sort((a, b) => sort === "rank" ? a.rank - b.rank : b[sort] - a[sort]);
  return <><div className="table-tools"><input aria-label="搜尋股票" placeholder="搜尋股票名稱或代號…" value={query} onChange={e => setQuery(e.target.value)}/><select value={industry} onChange={e => setIndustry(e.target.value)}><option value="All">全部產業</option>{industries.map(v => <option key={v}>{v}</option>)}</select><select value={rating} onChange={e => setRating(e.target.value)}><option value="All">全部評級</option>{(["Strong Buy", "Buy", "Watch", "Hold"] as Rating[]).map(v => <option key={v} value={v}>{ratingLabel[v]}</option>)}</select></div><div className="stock-table-wrap"><table className="stock-table"><thead><tr><th onClick={() => setSort("rank")}>排名 ↕</th><th>股票</th><th>產業</th><th>現價</th><th>基準合理價</th><th onClick={() => setSort("upsidePercent")}>潛在空間 ↕</th><th>TTM EPS</th><th>EPS 成長代理</th><th>P/E</th><th>PEG</th><th>ROE</th><th onClick={() => setSort("garpScore")}>GARP ↕</th><th>品質</th><th>評級</th><th>名次變化</th></tr></thead><tbody>{filtered.map(s => <tr key={s.ticker} onClick={() => onSelect(s.ticker)}><td><b>#{s.rank}</b></td><td><strong>{s.stockName}</strong><small>{s.ticker}</small></td><td>{s.industry}</td><td className="numeric">{money(s.currentPrice)}</td><td className="numeric">{money(s.fairValueBase)}</td><td className={`numeric ${s.upsidePercent >= 0 ? "positive":"negative"}`}>{s.upsidePercent >= 0 ? "+":""}{s.upsidePercent}%</td><td className="numeric">{s.ttmEps}</td><td className="numeric">{s.forecastEpsGrowth}%</td><td className="numeric">{s.pe}×</td><td className="numeric">{s.peg}</td><td className="numeric">{s.roe}%</td><td><span className="score-chip">{s.garpScore}</span></td><td>{s.qualityScore}</td><td><span className={`rating ${s.rating.toLowerCase().replace(" ", "-")}`}>{ratingLabel[s.rating]}</span></td><td><RankMove current={s.rank} previous={s.previousRank}/></td></tr>)}</tbody></table></div><p className="table-footer">顯示 {filtered.length}／{stocks.length} 檔追蹤股票 · 點擊任一列查看完整分析</p></>;
}

function Detail({ stock }: { stock: DailyStockAnalysis }) {
  const reasons=[`Latest EPS growth proxy: ${stock.forecastEpsGrowth}%`,`Latest revenue growth: ${stock.revenueGrowth}%`,`Estimated ROE: ${stock.roe}%`,`Potential return to base fair value: ${stock.upsidePercent}%`];
  const risks=[stock.cashFlowScore<50?"Latest free cash flow is negative":"End-market demand may be cyclical",stock.riskScore>=60?"Balance-sheet risk requires monitoring":"Valuation may compress as risk appetite changes","Licensed analyst-consensus EPS is not yet connected"];
  return <section className="detail-grid"><article className="panel investment-card"><div className="panel-head"><div><p className="overline">SELECTED STOCK ANALYSIS</p><h2>{stock.stockName} <span>{stock.ticker}</span></h2><small>{industryEnglish[stock.industry] ?? stock.industry} · Updated {stock.updatedAt.slice(0,10)} at {stock.updatedAt.slice(11,16)}</small></div><span className={`rating ${stock.rating.toLowerCase().replace(" ", "-")}`}>{ratingLabel[stock.rating]}</span></div><div className="investment-stats"><div><span>GARP score</span><strong>{stock.garpScore}</strong></div><div><span>Fair-value range</span><strong>NT${money(stock.fairValueLow)}–{money(stock.fairValueHigh)}</strong></div><div><span>Potential return</span><strong className={stock.upsidePercent >= 0 ? "positive":"negative"}>{stock.upsidePercent >= 0 ? "+":""}{stock.upsidePercent}%</strong></div></div><p className="conclusion">The TW-GARP eight-factor model evaluates growth, valuation, quality, cash flow, and financial risk together.</p><div className="reason-risk"><div><h3>Why it ranks</h3>{reasons.map(v => <p key={v}>✓ {v}</p>)}</div><div><h3>Key risks</h3>{risks.map(v => <p key={v}>△ {v}</p>)}</div></div></article><article className="panel"><div className="panel-head"><div><p className="overline">SCORE COMPOSITION</p><h2>Six-factor profile</h2></div></div><ScoreComposition stock={stock}/></article></section>;
}

export default function Dashboard() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const latest = tradingDates.at(-1)!;
  const initialDate = tradingDates.includes(params.get("date") ?? "") ? params.get("date")! : latest;
  const [date, setDate] = useState(initialDate); const [selected, setSelected] = useState("6669"); const [theme, setTheme] = useState<"light" | "dark">("light"); const [loading, setLoading] = useState(true);
  const snapshot = getSnapshot(date);
  useEffect(() => { const id = window.setTimeout(() => setLoading(false), 450); return () => clearTimeout(id); }, []);
  const pickDate = (value: string) => { setDate(value); setLoading(true); const next = new URLSearchParams(params.toString()); next.set("date", value); router.replace(`${pathname}?${next}`); window.setTimeout(() => setLoading(false), 280); };
  const stock = snapshot?.stocks.find(s => s.ticker === selected) ?? snapshot?.stocks[0];
  const kpis = useMemo(() => snapshot ? [
    ["Stocks analyzed", snapshot.stocks.length, 0, "Companies in the current real-data tracking universe"], ["Strong Buy", snapshot.stocks.filter(s => s.rating === "Strong Buy").length, 0, "GARP score of 85 or higher"], ["New entrants", snapshot.stocks.filter(s => s.previousRank === null).length, 0, "New to the ranking versus the previous session"], ["Positive EPS growth", snapshot.stocks.filter(s => s.forecastEpsGrowth > 0).length, 0, "Positive quarterly EPS/revenue growth proxy; not analyst revisions"], ["Below fair value", snapshot.stocks.filter(s => s.upsidePercent > 0).length, 0, "Current price below modeled base fair value"], ["PEG below 1", snapshot.stocks.filter(s => s.peg < 1).length, 0, "PEG below 1 using the latest growth proxy"], ["Average GARP", Math.round(snapshot.stocks.reduce((a,s)=>a+s.garpScore,0)/snapshot.stocks.length), 0, "Average GARP score across the tracking universe"], ["High risk", snapshot.stocks.filter(s => s.riskScore >= 60).length, 0, "Risk Score of 60 or higher"],
  ] as const : [], [snapshot]);

  if (loading) return <div className="dashboard" data-theme={theme}><header className="topbar"><div className="logo">G</div><b>GARP Analytics Taiwan</b></header><div className="page-shell skeleton-grid">{Array.from({length:12},(_,i)=><div className="skeleton" key={i}/>)}</div></div>;
  if (!snapshot || !stock) return <div className="state-card"><h1>No analysis snapshot</h1><p>The market may have been closed, or the data snapshot is not ready.</p><button onClick={() => pickDate(latest)}>Return to latest session</button></div>;
  const history=tradingDates.map(d=>snapshots[d].stocks.find(s=>s.ticker===stock.ticker)!).filter(Boolean);

  return <div className="dashboard" data-theme={theme}>
    <header className="topbar"><div className="brand-group"><div className="logo">G</div><div><b>GARP Analytics Taiwan</b><span>Quality Growth Dashboard</span></div></div><nav><a href="#ranking">Daily Ranking</a><a href="#analysis">Stock Analysis</a><a href="#methodology">Data & Methodology</a><button className="theme-toggle" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Toggle color mode">{theme === "light" ? "◐ Dark" : "☀ Light"}</button></nav></header>
    <main className="page-shell">
      <section className="dashboard-title"><div><p className="overline">TAIWAN EQUITY INTELLIGENCE</p><h1>Quality Growth Dashboard</h1><p>Daily rankings combining real closing prices, financial statements, fair value, earnings growth, and risk.</p></div><div className="freshness"><span>● REAL DATA</span><p>Snapshot date</p><b>{snapshot.analysisDate} · After close</b></div></section>
      <section className="date-filter"><div><b>Analysis date</b><span>Latest 7 valid trading sessions</span></div>{tradingDates.map(d => <button className={date === d ? "active" : ""} key={d} onClick={() => pickDate(d)}><small>{new Date(`${d}T00:00:00`).toLocaleDateString("en-US", { weekday:"short" })}</small>{shortDate(d)}</button>)}</section>
      <section className="kpi-grid">{kpis.map(([label,value,delta,hint]) => <KpiCard key={label} label={label} value={value} delta={delta} hint={hint}/>)}</section>
      <section className="alerts"><div className="section-title"><div><p className="overline">OPPORTUNITY & RISK MONITOR</p><h2>Important Signal Alerts</h2></div><span>{snapshot.stocks.length} stocks monitored</span></div><div className="alert-grid"><article className="opportunity"><b>◆ OPPORTUNITY</b><h3>{snapshot.stocks.filter(s=>s.peg<1).length} stocks with PEG below 1</h3><p>Calculated using the latest EPS and revenue growth proxy, not analyst consensus.</p></article><article className="opportunity"><b>◆ OPPORTUNITY</b><h3>{snapshot.stocks.filter(s=>s.upsidePercent>0).length} stocks below base fair value</h3><p>Fair value uses expected EPS × reasonable P/E across three scenarios.</p></article><article className="warning"><b>△ WARNING</b><h3>{snapshot.stocks.filter(s=>s.cashFlowScore<50).length} stocks with weak cash flow</h3><p>Latest operating cash flow less capital expenditure is negative.</p></article><article className="info"><b>● INFORMATION</b><h3>Analyst consensus not connected</h3><p>Expectation Score remains neutral at 50 to avoid fabricated revisions.</p></article></div></section>
      <section className="panel ranking-panel" id="ranking"><div className="panel-head"><div><p className="overline">DAILY SCREEN</p><h2>Real-data Tracking Universe: Top 10</h2><small>Calculated with the TW-GARP eight-factor model; not a full-market screen</small></div><span className="demo-pill">REAL DATA</span></div><StockTable stocks={snapshot.stocks} onSelect={setSelected}/></section>
      <section className="chart-grid"><article className="panel"><div className="panel-head"><div><p className="overline">COMPOSITE SCORE</p><h2>GARP Ranking</h2></div><span>Out of 100</span></div><RankingBars stocks={snapshot.stocks} selected={selected} onSelect={setSelected}/></article><article className="panel"><div className="panel-head"><div><p className="overline">VALUATION × GROWTH</p><h2>Opportunity Map</h2></div><span>Click a bubble to select</span></div><Scatter stocks={snapshot.stocks} selected={selected} onSelect={setSelected}/></article></section>
      <section className="chart-grid"><article className="panel"><div className="panel-head"><div><p className="overline">PRICE POSITIONING</p><h2>Price vs Fair Value</h2></div><span>● Price · ▬ Fair-value range</span></div><FairValueChart stocks={snapshot.stocks}/></article><article className="panel"><div className="panel-head"><div><p className="overline">DIVERSIFICATION</p><h2>Sector Distribution</h2></div><span>Tracking-universe Top 10</span></div><SectorChart stocks={snapshot.stocks}/></article></section>
      <div id="analysis"><Detail stock={stock}/></div>
      <section className="chart-grid"><article className="panel"><div className="panel-head"><div><p className="overline">EARNINGS TREND</p><h2>{stock.stockName} Quarterly EPS</h2></div><span>Actuals: 2025 Q1–2026 Q1</span></div><EpsChart stock={stock}/></article><article className="panel"><div className="panel-head"><div><p className="overline">SEVEN-SESSION TREND</p><h2>Ranking & Score Movement</h2></div><span>{stock.ticker}</span></div><div className="trend-cards"><div><span>GARP score</span><strong>{stock.garpScore}</strong><small>{stock.garpScore-history[0].garpScore>=0?"↑":"↓"} {Math.abs(stock.garpScore-history[0].garpScore)} points</small></div><div><span>Current rank</span><strong>#{stock.rank}</strong><small>{history[0].rank-stock.rank>=0?"↑":"↓"} {Math.abs(history[0].rank-stock.rank)} positions</small></div><div><span>Base fair value</span><strong>NT${money(stock.fairValueBase)}</strong><small>Financials × reasonable P/E</small></div><div><span>EPS growth proxy</span><strong>{stock.forecastEpsGrowth}%</strong><small>Latest actuals, not consensus</small></div></div><div className="mini-trend">{history.map((s,i)=><div key={s.analysisDate}><i style={{height:`${Math.max(15,s.garpScore)}%`}} title={`${s.analysisDate}: ${s.garpScore} points`}/><span>{shortDate(tradingDates[i])}</span></div>)}</div></article></section>
      <section className="panel events"><div className="panel-head"><div><p className="overline">CATALYSTS & RISKS</p><h2>Recent Data Events</h2></div><span>{stock.stockName}</span></div>{stock.latestEvents.map(event => <article key={`${event.date}${event.type}`}><time>{event.date}</time><i className={event.direction}/><div><b>{event.type === "官方收盤價更新" ? "Official closing-price update" : "First-quarter earnings"}</b><p>{event.type === "官方收盤價更新" ? `TWSE closing price: NT$${money(stock.currentPrice)}` : `Quarterly EPS and operating-margin results published`}</p><a href={event.url} target="_blank" rel="noreferrer">{event.type === "官方收盤價更新" ? "Taiwan Stock Exchange" : "MOPS / structured financial data"} ↗</a></div><span className={event.direction}>{event.direction === "positive" ? "Positive" : event.direction === "negative" ? "Negative" : "Neutral"}</span></article>)}</section>
      <section className="methodology panel" id="methodology"><div><p className="overline">DATA & METHODOLOGY</p><h2>Transparent, Traceable Scoring</h2><p>The project’s eight-factor, 10-point model combines EPS growth, P/E, PEG, ROE, P/B, dividends, free cash flow, leverage, and expectations. P/E never determines value in isolation.</p></div><div><b>Data limitation</b><p>Licensed analyst consensus EPS is not connected. Expectation Score stays neutral at 50. “EPS growth proxy” combines recent actual EPS and revenue growth; it is not an analyst forecast.</p></div><div><b>Data sources</b><p><a href="https://www.twse.com.tw/" target="_blank" rel="noreferrer"><strong>Taiwan Stock Exchange</strong> ↗</a><br/>Daily closing prices, P/E, P/B, and dividend yield.</p><p><a href="https://mops.twse.com.tw/" target="_blank" rel="noreferrer"><strong>Market Observation Post System</strong> ↗</a><br/>Consolidated corporate financial statements.</p><p><a href="https://finmind.github.io/" target="_blank" rel="noreferrer"><strong>FinMind</strong> ↗</a><br/>Structured TWSE/MOPS financial-statement interface.</p></div></section>
    </main><footer><b>GARP Analytics Taiwan</b><span>Real-data tracking universe · Not investment advice</span><span>© 2026</span></footer>
  </div>;
}
